#pragma once

#define FLECTRON_ENABLE_PROFILING (0)
#if FLECTRON_ENABLE_PROFILING
  #include <optick.h>
  #define FLECTRON_PROFILE_FRAME(...) OPTICK_FRAME(__VA_ARGS__)
  #define FLECTRON_PROFILE_EVENT(...) OPTICK_EVENT(__VA_ARGS__)
  #define FLECTRON_PROFILE_TAG(NAME, ...) OPTICK_TAG(NAME, __VA_ARGS__)
  #define FLECTRON_PROFILE_EVENT_DYNAMIC(NAME) OPTICK_EVENT_DYNAMIC(NAME)
  #define FLECTRON_PROFILE_THREAD(...) OPTICK_THREAD(__VA_ARGS__)
#else
  #define FLECTRON_PROFILE_FRAME(...)
  #define FLECTRON_PROFILE_EVENT(...)
  #define FLECTRON_PROFILE_TAG(NAME, ...)
  #define FLECTRON_PROFILE_EVENT_DYNAMIC(NAME)
  #define FLECTRON_PROFILE_THREAD(...)
#endif
