FROM flectron:latest

WORKDIR /flectron/build

# when running with local changes:
# RUN cmake -D CMAKE_BUILD_TYPE=Debug /flectron
# RUN cmake --build . --config Debug -- -j"$(nproc)"
# COPY . /flectron

RUN cmake -D CMAKE_BUILD_TYPE=Debug /flectron
RUN cmake --build . --config Debug -- -j"$(nproc)"

WORKDIR /flectron/build/examples/
# CMD ./flectron-piday
# CMD ./flectron-terrain
CMD ./flectron-demo
